high_correlation_threshold: 0.9
low_risk_correlation_threshold: 0.01
similar_risk_correlation_threshold: 0.01
low_variance_percent_threshold: 0.01
iqr_factor: 1.5
lower_bound_outliers_capping: 0.0
upper_bound_outliers_capping: 10.0
n_events_to_plot: 5
first_event_to_plot: 0
min_entries_threshold: 10



