columns:
    metadata:
        event_id:
            description: collision identifier
            kept: true

        mission_id:
            description: mission identifier
            kept: false
        
        c_object_type:
            description: type of object at risk of collision
            kept: false
    
    collision:
        risk:
            description: value to be predicted
            kept: true
            timeseries_plot: true

        max_risk_estimate:
            description: maximum risk estimate
            kept: false

        max_risk_scaling:
            description: maximum risk scaling used to calculate the maximum risk estimate
            kept: false
        
        miss_distance:
            description: ''
            timeseries_plot: true

        mahalanobis_distance:
            description: ''
            timeseries_plot: true

        geometry:
            time_to_tca:
                description: time interval between the creation of the CDM and the time of closest approach [days]
                kept: true

            relative_speed:
                description: relative speed between the chaser and the target at the time of closest approach [m/s]
                timeseries_plot: false

            geocentric_latitude:
                description: geocentric latitude of the point of closest approach [deg]
                timeseries_plot: true

            azimuth:
                description: azimuth angle of the relative velocity vector [deg]
                timeseries_plot: false

            elevation:
                description: elevation angle of the relative velocity vector [deg]
                timeseries_plot: true

            position: # relative position between the chaser and the target at the time of closest approach
                relative_position_n:
                    description: normal (cross-track) [m]
                    timeseries_plot: true

                relative_position_r:
                    description: radial [m]
                    timeseries_plot: true

                relative_position_t:
                    description: transverse (along-track) [m]
                    timeseries_plot: true

            velocity: # relative velocity between the chaser and the target at the time of closest approach
                relative_velocity_n:
                    description: normal (cross-track) [m/s]
                    timeseries_plot: true

                relative_velocity_r:
                    description: radial [m/s]
                    timeseries_plot: true

                relative_velocity_t:
                    description: transverse (along-track) [m/s]
                    timeseries_plot: true

    solar_activity:
        F10:
            description: 10.7 cm radio flux index [10−2210−22 W/(m2m2 Hz)]
            timeseries_plot: true

        AP:
            description: daily planetary geomagnetic amplitude index
            timeseries_plot: true

        F3M:
            description: 81-day running mean of F10.7 (over 3 solar rotations) [10−2210−22 W/(m2m2 Hz)]
            timeseries_plot: true

        SSN:
            description: Wolf sunspot number
            timeseries_plot: true

    object: # on the dataset, the x_ prefix represents the chaser (c) or the target (t)
        physical_properties:
            target:
                t_cd_area_over_mass:
                    description: ballistic coefficient [m2m2/kg]
                    timeseries_plot: false

                t_cr_area_over_mass:
                    description: ''
                    timeseries_plot: false

                t_sedr:
                    description: energy dissipation rate [W/kg]
                    timeseries_plot: false

                t_rcs_estimate:
                    description: radar cross-sectional area [m2m2]
                    timeseries_plot: false

                t_span:
                    description: size used by the collision risk calculation algorithm (minimum diameter of 2 m assumed for the chaser) [m]
                    kept: false
            chaser:
                c_cd_area_over_mass:
                    description: ballistic coefficient [m2m2/kg]
                    timeseries_plot: false

                c_cr_area_over_mass:
                    description: ''
                    timeseries_plot: false

                c_sedr:
                    description: energy dissipation rate [W/kg]
                    timeseries_plot: false

                c_rcs_estimate:
                    description: radar cross-sectional area [m2m2]
                    timeseries_plot: false
                    kept: false

                c_span:
                    description: size used by the collision risk calculation algorithm (minimum diameter of 2 m assumed for the chaser) [m]
                    kept: false
        
        orbit:
            target:
                t_h_apo:
                    description: apogee [km]
                    timeseries_plot: false

                t_h_per:
                    description: perigee [km]
                    timeseries_plot: true

                t_j2k_inc:
                    description: inclination [deg]
                    timeseries_plot: false

                t_j2k_sma:
                    description: semi-major axis [km]
                    timeseries_plot: false

                t_j2k_ecc:
                    description: eccentricity
                    timeseries_plot: false
            chaser:
                c_h_apo:
                    description: apogee [km]
                    timeseries_plot: false

                c_h_per:
                    description: perigee [km]
                    timeseries_plot: true

                c_j2k_inc:
                    description: inclination [deg]
                    timeseries_plot: false

                c_j2k_sma:
                    description: semi-major axis [km]
                    timeseries_plot: false
                c_j2k_ecc:
                    description: eccentricity
                    timeseries_plot: false

            observation:
                target:
                    t_obs_available:
                        description: number of observations available for orbit determination (per CDM)
                        timeseries_plot: false

                    t_obs_used:
                        description: number of observations used for orbit determination (per CDM)
                        timeseries_plot: false
                        kept: false

                    t_time_lastob_end:
                        description: end of the time interval in days (with respect to the CDM creation epoch) of the last accepted observation used in the orbit determination
                        timeseries_plot: true
                        kept: false

                    t_time_lastob_start:
                        description: start of the time in days (with respect to the CDM creation epoch) of the last accepted observation used in the orbit determination
                        timeseries_plot: true
                        kept: false
                chaser:
                    c_obs_available:
                        description: number of observations available for orbit determination (per CDM)
                        timeseries_plot: false

                    c_obs_used:
                        description: number of observations used for orbit determination (per CDM)
                        timeseries_plot: false
                        kept: false

                    c_time_lastob_end:
                        description: end of the time interval in days (with respect to the CDM creation epoch) of the last accepted observation used in the orbit determination
                        timeseries_plot: true
                        kept: false

                    c_time_lastob_start:
                        description: start of the time in days (with respect to the CDM creation epoch) of the last accepted observation used in the orbit determination
                        timeseries_plot: true
                        kept: false

            metrics:
                target:
                    t_actual_od_span:
                        description: actual interval of orbit determination [days]
                        timeseries_plot: false

                    t_recommended_od_span:
                        description: recommended interval of orbit determination [days]
                        timeseries_plot: false
                        kept: false

                    t_weighted_rms:
                        description: weighted root mean square
                        timeseries_plot: true

                    t_residuals_accepted:
                        description: accepted residuals
                        timeseries_plot: false
                        kept: false
                chaser:
                    c_actual_od_span:
                        description: actual interval of orbit determination [days]
                        timeseries_plot: false

                    c_recommended_od_span:
                        description: recommended interval of orbit determination [days]
                        timeseries_plot: false
                        kept: false

                    c_weighted_rms:
                        description: weighted root mean square
                        timeseries_plot: true

                    c_residuals_accepted:
                        description: accepted residuals
                        timeseries_plot: false
                        kept: false

        velocity:
            sigma:
                target:
                    t_sigma_rdot:
                        description: radial velocity [m/s]
                        kept: false

                    t_sigma_ndot:
                        description: cross-track velocity [m/s]
                        kept: false

                    t_sigma_tdot:
                        description: along-track velocity [m/s]
                        kept: false
                chaser:
                    c_sigma_rdot:
                        description: radial velocity [m/s]
                        kept: false

                    c_sigma_ndot:
                        description: cross-track velocity [m/s]
                        kept: false

                    c_sigma_tdot:
                        description: along-track velocity [m/s]
                        kept: false

            correlation:
                target:
                    t_ctdot_rdot: 
                        description: along-track velocity vs radial velocity
                        kept: false

                    t_cndot_rdot: 
                        description: cross-track velocity vs radial velocity
                        kept: false

                    t_cndot_tdot: 
                        description: along-track velocity vs cross-track velocity
                        kept: false
                chaser:
                    c_ctdot_rdot: 
                        description: along-track velocity vs radial velocity
                        kept: false

                    c_cndot_rdot: 
                        description: cross-track velocity vs radial velocity
                        kept: false

                    c_cndot_tdot: 
                        description: along-track velocity vs cross-track velocity
                        kept: false

        position:
            determinant:
                target:
                    t_position_covariance_det:
                        description: covariance determinant (~volume)
                        kept: false
                chaser:
                    c_position_covariance_det:
                        description: covariance determinant (~volume)
                        kept: false
                    
            correlation:
                target:
                    t_cn_r:
                        description: cross-track position vs radial position
                        kept: false

                    t_cn_t:
                        description: cross-track position vs along-track position
                        kept: false

                    t_ct_r:
                        description: along-track position vs radial position
                        kept: false
                chaser:
                    c_cn_r:
                        description: cross-track position vs radial position
                        kept: false

                    c_cn_t:
                        description: cross-track position vs along-track position
                        kept: false

                    c_ct_r:
                        description: along-track position vs radial position
                        kept: false

            sigma:
                target:
                    t_sigma_n:
                        description: cross-track position [m]
                        kept: false

                    t_sigma_t:
                        description: along-track position [m]
                        kept: false

                    t_sigma_r:
                        description: radial position [m]
                        kept: false
                chaser:
                    c_sigma_n:
                        description: cross-track position [m]
                        kept: false

                    c_sigma_t:
                        description: along-track position [m]
                        kept: false

                    c_sigma_r:
                        description: radial position [m]
                        kept: false

        velocity_position:
            correlation:
                target:
                    t_cndot_n:
                        description: cross-track velocity vs cross-track position
                        kept: false

                    t_cndot_r:
                        description: cross-track velocity vs radial position
                        kept: false

                    t_cndot_t:
                        description: cross-track velocity vs along-track position
                        kept: false

                    t_crdot_n:
                        description: ''
                        kept: false

                    t_crdot_r:
                        description: ''
                        kept: false

                    t_crdot_t:
                        description: ''
                        kept: false

                    t_ctdot_r:
                        description: along-track velocity vs radial position
                        kept: false

                    t_ctdot_n:
                        description: ''
                        kept: false

                    t_ctdot_t:
                        description: along-track velocity vs along-track position
                        kept: false
                chaser:
                    c_cndot_n:
                        description: cross-track velocity vs cross-track position
                        kept: false

                    c_cndot_r:
                        description: cross-track velocity vs radial position
                        kept: false

                    c_cndot_t:
                        description: cross-track velocity vs along-track position
                        kept: false

                    c_ctdot_r:
                        description: along-track velocity vs radial position
                        kept: false

                    c_ctdot_n:
                        description: ''
                        kept: false

                    c_ctdot_t:
                        description: along-track velocity vs along-track position
                        kept: false

                    c_crdot_n:
                        description: ''
                        kept: false

                    c_crdot_r:
                        description: ''
                        kept: false

                    c_crdot_t:
                        description: ''
                        kept: false
